{{- if .Values.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-smtp"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  DAKARA_EMAIL_URL: {{ .Values.smtp.url | quote }}
{{- end }}
