environments:
  default:
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
---
releases:
  - name: registry
    chart: ../../charts/registry
    values:
      - auth:
          htpasswd: "{{ .Values.auth.htpasswd }}"
      - s3: {{ toYaml .Values.s3 | nindent 10 }}
      - ingress:
          host: registry.{{ .Values.domain }}
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-compress@kubernetescrd"
            cert-manager.io/cluster-issuer: letsencrypt
