environments:
  default:
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
---
releases:
  - name: jellyswarrm
    chart: ../../charts/jellyswarrm
    values:
      - image:
          repository: ghcr.io/llukas22/jellyswarrm
          tag: main@sha256:f3b2782fcb0a1c90a32fdfa3d9796c6910b2d245fb1f657d147a9c711e36ac01 # renovate
      - updateStrategy:
          type: Recreate
      - admin:
          username: "{{ .Values.jellyswarrm.admin.username }}"
          password: "{{ .Values.jellyswarrm.admin.password }}"
      - ingress:
          host: jellyfin.{{ .Values.domain }}
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            # traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-compress@kubernetescrd"
            cert-manager.io/cluster-issuer: letsencrypt
