environments:
  default:
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
---
releases:
  - name: jellyswarrm
    chart: ../../charts/jellyswarrm
    values:
      - image:
          repository: ghcr.io/llukas22/jellyswarrm
          tag: main@sha256:464da56e5c5d74d80ea369476c95f70820f94266793eb590423e9688c5aeab81 # renovate
      - updateStrategy:
          type: Recreate
      - admin:
          username: "{{ .Values.jellyswarrm.admin.username }}"
          password: "{{ .Values.jellyswarrm.admin.password }}"
      - ingress:
          host: jellyfin.{{ .Values.domain }}
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            # traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-compress@kubernetescrd"
            cert-manager.io/cluster-issuer: letsencrypt
