environments:
  default:
    values:
      - loki:
          replicas: 2
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: grafana-community
    url: ghcr.io/grafana-community/helm-charts
    oci: true

releases:
  - name: grafana
    chart: grafana-community/grafana
    version: 12.3.1
    values:
      - deploymentStrategy:
          type: Recreate
      - adminPassword: {{ .Values.grafana.adminPassword }}
      - grafana.ini:
          server:
            root_url: https://grafana.{{ .Values.domain }}
          auth:
            disable_login_form: true
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki:3100
                isDefault: true
                jsonData:
                  timeout: 60
                  maxLines: 1000
      - persistence:
          enabled: true
      - ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-compress@kubernetescrd"
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - grafana.{{ .Values.domain }}
          tls:
            - secretName: grafana.{{ .Values.domain }}-tls
              hosts:
                - grafana.{{ .Values.domain }}
  - name: loki
    chart: grafana-community/loki
    version: 13.6.3
    values:
      # https://github.com/grafana-community/helm-charts/blob/ccc85c03fb101eb787352015f615cba2568fc0e0/charts/loki/monolithic-values.yaml
      - loki:
          auth_enabled: false
          commonConfig:
            replication_factor: {{ .Values.loki.replicas }}
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
            max_concurrent: 2
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
            s3: {{ .Values.loki.s3 | toYaml | nindent 14 }}
          compactor:
            working_directory: /var/loki/data/retention
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
            delete_request_store: s3
          limits_config:
            retention_period: 30d
      - deploymentMode: Monolithic
      - singleBinary:
          replicas: {{ .Values.loki.replicas }}
          resources:
            limits:
              cpu: 3
              memory: 4Gi
            requests:
              cpu: 2
              memory: 2Gi
          extraEnv:
            # Keep a little bit lower than memory limits
            - name: GOMEMLIMIT
              value: 3750MiB
      - chunksCache:
          enabled: false
          # # default is 500MB, with limited memory keep this smaller
          # writebackSizeLimit: 10MB
      # # Enable minio for storage
      # - minio:
      #     enabled: true
      # Zero out replica counts of other deployment modes
      - backend:
          replicas: 0
      - read:
          replicas: 0
      - write:
          replicas: 0
      - ingester:
          replicas: 0
      - querier:
          replicas: 0
      - queryFrontend:
          replicas: 0
      - queryScheduler:
          replicas: 0
      - distributor:
          replicas: 0
      - compactor:
          replicas: 0
      - indexGateway:
          replicas: 0
      - bloomCompactor:
          replicas: 0
      - bloomGateway:
          replicas: 0
      - gateway:
          enabled: false
      - resultsCache:
          enabled: false
      - test:
          enabled: false
      - lokiCanary:
          enabled: false
  - name: alloy
    chart: grafana/alloy
    version: 1.8.1
    values:
      - alloy:
          configMap:
            content: |-
              {{ readFile "config.alloy" | nindent 14 }}
