environments:
  default:
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: grafana-community
    url: ghcr.io/grafana-community/helm-charts
    oci: true

releases:
  - name: grafana
    chart: grafana-community/grafana
    version: 12.3.0
    values:
      - deploymentStrategy:
          type: Recreate
      - adminPassword: {{ .Values.grafana.adminPassword }}
      - grafana.ini:
          server:
            root_url: https://grafana.{{ .Values.domain }}
          auth:
            disable_login_form: true
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki:3100
                isDefault: true
                jsonData:
                  timeout: 60
                  maxLines: 1000
      - persistence:
          enabled: true
      - ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-compress@kubernetescrd"
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - grafana.{{ .Values.domain }}
          tls:
            - secretName: grafana.{{ .Values.domain }}-tls
              hosts:
                - grafana.{{ .Values.domain }}
  - name: loki
    chart: grafana-community/loki
    version: 13.6.2
    values:
      # https://github.com/grafana-community/helm-charts/blob/ccc85c03fb101eb787352015f615cba2568fc0e0/charts/loki/monolithic-values.yaml
      - loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
            max_concurrent: 2
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
            s3: {{ .Values.loki.s3 | toYaml | nindent 14 }}
      - deploymentMode: Monolithic
      - singleBinary:
          replicas: 1
          resources:
            limits:
              cpu: 3
              memory: 4Gi
            requests:
              cpu: 2
              memory: 2Gi
          extraEnv:
            # Keep a little bit lower than memory limits
            - name: GOMEMLIMIT
              value: 3750MiB
      - chunksCache:
          enabled: false
          # # default is 500MB, with limited memory keep this smaller
          # writebackSizeLimit: 10MB
      # # Enable minio for storage
      # - minio:
      #     enabled: true
      # Zero out replica counts of other deployment modes
      - backend:
          replicas: 0
      - read:
          replicas: 0
      - write:
          replicas: 0
      - ingester:
          replicas: 0
      - querier:
          replicas: 0
      - queryFrontend:
          replicas: 0
      - queryScheduler:
          replicas: 0
      - distributor:
          replicas: 0
      - compactor:
          replicas: 0
      - indexGateway:
          replicas: 0
      - bloomCompactor:
          replicas: 0
      - bloomGateway:
          replicas: 0
      - test:
          enabled: false
      - lokiCanary:
          enabled: false
  - name: alloy
    chart: grafana/alloy
    version: 1.8.1
    values:
      - alloy:
          configMap:
            # https://grafana.com/docs/alloy/latest/collect/logs-in-kubernetes/#pod-logs
            content: |-
              logging {
                level = "info"
                format = "logfmt"
              }

              loki.write "loki" {
                endpoint {
                  url = "http://loki:3100/loki/api/v1/push"
                }
              }

              // discovery.kubernetes allows you to find scrape targets from Kubernetes resources.
              // It watches cluster state and ensures targets are continually synced with what is currently running in your cluster.
              discovery.kubernetes "pod" {
                role = "pod"
                // Restrict to pods on the node to reduce cpu & memory usage
                selectors {
                  role = "pod"
                  field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
                }
              }

              // discovery.relabel rewrites the label set of the input targets by applying one or more relabeling rules.
              // If no rules are defined, then the input targets are exported as-is.
              discovery.relabel "pod_logs" {
                targets = discovery.kubernetes.pod.targets

                // Label creation - "namespace" field from "__meta_kubernetes_namespace"
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  action = "replace"
                  target_label = "namespace"
                }

                // Label creation - "pod" field from "__meta_kubernetes_pod_name"
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  action = "replace"
                  target_label = "pod"
                }

                // Label creation - "container" field from "__meta_kubernetes_pod_container_name"
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  action = "replace"
                  target_label = "container"
                }

                // Label creation -  "app" field from "__meta_kubernetes_pod_label_app_kubernetes_io_name"
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
                  action = "replace"
                  target_label = "app"
                }

                // Label creation -  "job" field from "__meta_kubernetes_namespace" and "__meta_kubernetes_pod_container_name"
                // Concatenate values __meta_kubernetes_namespace/__meta_kubernetes_pod_container_name
                rule {
                  source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
                  action = "replace"
                  target_label = "job"
                  separator = "/"
                  replacement = "$1"
                }

                // Label creation - "__path__" field from "__meta_kubernetes_pod_uid" and "__meta_kubernetes_pod_container_name"
                // Concatenate values __meta_kubernetes_pod_uid/__meta_kubernetes_pod_container_name.log
                rule {
                  source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
                  action = "replace"
                  target_label = "__path__"
                  separator = "/"
                  replacement = "/var/log/pods/*$1/*.log"
                }

                // Label creation -  "container_runtime" field from "__meta_kubernetes_pod_container_id"
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_id"]
                  action = "replace"
                  target_label = "container_runtime"
                  regex = `^(\S+):\/\/.+$`
                  replacement = "$1"
                }
              }

              // loki.source.kubernetes tails logs from Kubernetes containers using the Kubernetes API.
              loki.source.kubernetes "pod_logs" {
                targets    = discovery.relabel.pod_logs.output
                forward_to = [loki.process.pod_logs.receiver]
              }

              // loki.process receives log entries from other Loki components, applies one or more processing stages,
              // and forwards the results to the list of receivers in the component's arguments.
              loki.process "pod_logs" {
                stage.static_labels {
                  values = {
                    cluster = "nanak8s",
                  }
                }

                forward_to = [loki.write.loki.receiver]
              }
