image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:06a2722f7788019eb43a0a401d9469037b94ce4845deff4d970490ec25f52687
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
