image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:43c8669e11bcaf8697c3cbe157d9c9d3078ebd21ca97e5f12ecdfd854c01f626
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
