image:
  repository: ghcr.io/japan7/nanalook
  tag: main@sha256:323e237582949fd5ef4de238ee4eafa8f48f4ecc59bba20d89a8d4ffc5d5fcbd
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  clientUsername: ""
  clientPassword: ""
  customClientId: ""
  customClientUsername: ""

ingress:
  host: ""
  annotations: {}
