image:
  repository: ghcr.io/tama-github/wvtr
  tag: master@sha256:aca41fc0a0f1268c8703cc175bf2066fc2dd9384cbcb2c08a00375d6c68d0f76
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

config: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
