image:
  repository: ghcr.io/tama-github/wvtr
  tag: master@sha256:7d58a34aae3ea3c7a25c9d232a257fd144d103a706aa14ab0e0d2f058d9b83cf
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

config: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
