image:
  repository: ghcr.io/tama-github/wvtr
  tag: master@sha256:ccc298ff903fc2fef5df75bbb8f5525735a5f7245eecc9d5cfe454f62247d7c3
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

config: ""

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}

ingress:
  host: ""
  annotations: {}
