image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:21e30ea7cae535e24ff299024872be35e6ab67252cd255f73718003c936cb68d
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
