image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:1de1289baa15d1fbfbb451bd6e5f31b5cb3a01ba2e9f89b2cd54a66df327ff6b
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
