image:
  repository: ghcr.io/japan7/dakara-client-web
  tag: master@sha256:a5cffb7ce71e0fb8d53367b52b503034a0da4fc46db90aa9b36d4dec2f23b574
  pullPolicy: ""

replicaCount: 1

affinity: {}

ingress:
  host: ""
  annotations: {}
