# scheduler for tasks (apscheduler)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-scheduler"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/secret-smtp.yaml") . | sha256sum }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          workingDir: /app/dakara_server
          env:
            {{- include "dakara.env" . | nindent 12 }}
          command: ["/app/dakara_server/manage.py"]
          args: ["runapscheduler"]
