image:
  repository: ghcr.io/japan7/nanacount
  tag: main@sha256:7dcf5058321b0adf07240a89f07e88333d0e3ab0773f9670e3ad0f0f074b4ba6
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

ingress:
  host: ""
  annotations: {}

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}
