image:
  repository: ghcr.io/japan7/nanacount
  tag: main@sha256:b754c6f1095ed137d60c7481df54c7ec3a89b1c0f8a312ffee16626d2651c5d7
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

ingress:
  host: ""
  annotations: {}

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}
