image:
  repository: ghcr.io/japan7/nanacount
  tag: main@sha256:07982d3bf6d2818ba503687af113e7589af9ec7264816e99e07dbd7698cc5215
  pullPolicy: ""

replicaCount: 1

updateStrategy:
  type: RollingUpdate

ingress:
  host: ""
  annotations: {}

persistence:
  accessMode: ReadWriteOnce
  size: 1Gi
  labels: {}
