{{- if .Values.dump.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-dump"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dump
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  dump.sh: |
    #!/bin/sh -xe

    DUMP_DIR=/dump/
    gel dump --all --format=dir $DUMP_DIR

    curl -fsSL https://rclone.org/install.sh | bash
    RCLONE_REMOTE=":s3,endpoint=https://$S3_HOSTNAME,access_key_id=$S3_ACCESS_KEY,secret_access_key=$S3_SECRET_KEY:$S3_BUCKET"
    rclone sync "$DUMP_DIR" "$RCLONE_REMOTE"
{{- end }}
