image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:05bf032c103f222c3f55cee0af541363c5f339349932c131da03e4d642f6a8fc
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
