image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:a5b97c784e51e48e91b65ebb35aaefd678cc1e4895cf628fd373a13cae2f9022
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
