image:
  repository: ghcr.io/japan7/nanaoidc
  tag: main@sha256:fb1224490f09dc0b6867dea66cd8435f4126d3bcab5423499186dcbd55181c98
  pullPolicy: ""

replicaCount: 1

config: ""

ingress:
  host: ""
  annotations: {}

forwardAuth:
  hosts: []
  annotations: {}
