image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:47b54e666261d749a64a5f1dfabc5786e21559dc4dd684e8139286851656659e
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
