image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:b2fb9168c43839d883c90e47b82588f4da73c51e2026e8e736eee9bef977a301
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
