image:
  repository: ghcr.io/japan7/waicolle-web
  tag: main@sha256:ccd46961bac0a7dfe5d0d661334812edfb0061dbce57da9351c6227a26af0154
  pullPolicy: ""

replicaCount: 1

nanapi:
  url: ""
  username: ""
  password: ""

defaultClientId: ""

ingress:
  host: ""
  annotations: {}
