apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-s3"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.s3.accessKey }}"
  password: "{{ .Values.s3.secretKey }}"
