apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-auth"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: "{{ .Values.auth.htpasswd }}"
