image:
  repository: ghcr.io/nextfire/vocal-remover-api
  tag: main@sha256:2afb19763c41cb7721c785c6e213747e852737561f7ab124abaae91c98ce43c6
  pullPolicy: ""

replicaCount: 1

nodeSelector: {}
affinity: {}

ingress:
  enabled: false
  host: ""
  annotations: {}
