image:
  repository: ghcr.io/nextfire/vocal-remover-api
  tag: main@sha256:fa814195fcc4fca376fd83a50d1f0aa8d3b736571bdece10ed044873b19f4bff
  pullPolicy: ""

replicaCount: 1

nodeSelector: {}
affinity: {}

ingress:
  enabled: false
  host: ""
  annotations: {}
