image:
  repository: ghcr.io/nextfire/vocal-remover-api
  tag: main@sha256:1ceb2946371561f014e0e8785b1f67f6853497e9fe4e136d60a1e838c7cdb4c0
  pullPolicy: ""

replicaCount: 1

nodeSelector: {}
affinity: {}

ingress:
  enabled: false
  host: ""
  annotations: {}
