image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:7df00bb4d068e22fc9dfe0f486fab2c90dd2422c95b0f4f5ce837082d698cf3a
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
