image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:266a40859e5dfc4f1f41ab10065d01cf9c7056d5f067cbed30f3dfcdb066fd67
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
