image:
  repository: ghcr.io/japan7/producer
  tag: main@sha256:55c25842e9aeb7c5219de2f3f229e7fb8dd131a7e9c0a2fb46ba2cf45d64ff38
  pullPolicy: ""

replicaCount: 1

affinity: {}

upload:
  baseUrl: ""
  adminToken: ""

s3:
  endpoints: []
  secure: false
  keyId: ""
  secret: ""

ingress:
  host: ""
  annotations: {}
