environments:
  default:
    secrets:
      - ../globals.sops.yaml
      - default.sops.yaml
---
repositories:
  - name: valkey
    url: https://valkey.io/valkey-helm

releases:
  - name: dakara-cnpg-18
    chart: ../../charts/cnpg-cluster
    values:
      - release: 18
      - storage:
          size: 5Gi
      - postgresql:
          parameters:
            max_slot_wal_keep_size: "2GB"
      - backups:
          enabled: true
          s3: {{ toYaml .Values.cnpg.s3 | nindent 12 }}
  - name: dakara-valkey
    chart: valkey/valkey
    version: 0.11.0
  - name: dakara
    chart: ../../charts/dakara
    values:
      - nodeSelector:
          kubernetes.io/arch: amd64
      - cnpg:
          secretName: dakara-cnpg-18-app
      - redis:
          host: redis://dakara-valkey:6379
      - secretKey: "{{ .Values.server.secretKey }}"
      - allowedHosts: "dakara-api.dakara,dakara.{{ .Values.domain }}"
      - superuser:
          username: "{{ .Values.server.superuser.username }}"
          email: "{{ .Values.server.superuser.email }}"
          password: "{{ .Values.server.superuser.password }}"
      - smtp:
          enabled: true
          sender: "{{ .Values.server.smtp.sender }}"
          url: "submission://{{ .Values.smtp.username }}:{{ .Values.smtp.password }}@{{ .Values.smtp.host }}"
      - ingress:
          host: dakara.{{ .Values.domain }}
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.traefik.namespace }}-compress@kubernetescrd"
            cert-manager.io/cluster-issuer: letsencrypt
  - name: dakara-server
    chart: ../../charts/dakara-server
    values:
      - image:
          repository: ghcr.io/japan7/dakara-server
          tag: update-deps@sha256:a88e15ca545f0f7af4aa5cbb66b444f48c4543ea101359a85221e3339120b8ff # renovate
      - secretKey: "{{ .Values.server.secretKey }}"
      - smtp:
          sender: "{{ .Values.server.smtp.sender }}"
          host: "{{ .Values.smtp.host }}"
          user: "{{ .Values.smtp.username }}"
          password: "{{ .Values.smtp.password }}"
  - name: dakara-client
    chart: ../../charts/dakara-client
    values:
      - affinity:
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - dakara-server
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - dakara-server
                  topologyKey: kubernetes.io/hostname
