apiVersion: v1
kind: Endpoints
metadata:
  name: garage-proxy
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
subsets:
  - hosts:
      {{- range .Values.garage.hosts }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - port: 3900
