apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: garage-proxy-cors
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  headers:
    {{ toYaml .Values.ingress.corsPolicy | nindent 4 }}
